###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
import numpy as np

In [ ]:
a=np.zeros(10)
np.put(a, 4, 1)

print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a=int(input('enter no 1'))
b=int(input('enter no 2'))
c=np.random.random((a,b)).reshape(a,b)
print(c)
np.mean(c)

enter no 12
enter no 25
[[0.79606903 0.87238857 0.11251012 0.61451815 0.84932836]
 [0.51714188 0.74357272 0.66540588 0.49095461 0.21499721]]


np.float64(0.5876886525460625)

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:

def border_array(a, b):
    arr = np.zeros((a, b), dtype=int)

    arr[0, :] = 1
    arr[-1, :] = 1
    arr[:, 0] = 1
    arr[:, -1] = 1

    return arr

# Example
print(border_array(4, 4))


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:


v = np.linspace(0, 1, 12)[1:-1]
print(v)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
a2=np.arange(0,4).isd(5)
a2

ValueError: cannot reshape array of size 4 into shape (5,)