# creating numpy array

In [ ]:
import numpy as np

a= np.array([1,2,3]) #1d numpy array/vector
print(a)

[1 2 3]


In [ ]:
b =np.array([[1,2,3],[4,5,6]])
print(b)      #2d numpy array/martrix

[[1 2 3]
 [4 5 6]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
#np.arange
np.arange(1,11) #same as range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#with reshape
np.arange(1,15).reshape(7,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [ ]:
#np.ones and np.zeroes (for initialise values)

np.ones((3,4)) #make all the values 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.71277448, 0.08342381, 0.46628691, 0.87211201],
       [0.47318628, 0.05466582, 0.41655974, 0.90697988],
       [0.7476194 , 0.16421004, 0.17063912, 0.71739386]])

In [ ]:
#np.linspace (linearly spaced)
np.linspace(-10,10,10) #it will generate 10 no. b/w -10 to 10 all with equally spaced

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(5) #by default dtype of nparray is float

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# array attributes

In [ ]:
a1= np.arange(10)
a2= np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndim gives the dimension of array
a2.ndim

2

In [ ]:
#shape tells how many items in that dimension i.e rows,colu
a2.shape

(3, 4)

In [ ]:
#size
a3.size #total no of elements

8

In [ ]:
#itemsize
#tells the size of each item in memory

In [ ]:
#dtype tell data type of items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# changing data type

In [ ]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# array operations

In [ ]:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#scalar operations
# arithmetic

print(a1 * 2)

print(a2 + 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [ ]:
#relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector opeartions
#arithmetic

print(a1+a2)
print(a1*a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


# Array functions

In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[52., 66., 57.],
       [27., 23., 95.],
       [80., 40., 40.]])

In [ ]:
#max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

95.0
23.0
480.0
1477227248640000.0


In [ ]:
# 0-> col, 1-> row
#max/min/sum/prod in particular row/col
print(np.max(a1,axis=1))
print(np.max(a1,axis=0))

[66. 95. 80.]
[80. 66. 95.]


In [ ]:
#mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))   #for particulars rows & col too

53.333333333333336
52.0
22.588099128129887
510.22222222222223


In [ ]:
# dot product
a2= np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#lof & exponenets
print(np.exp(a1))

[[3.83100800e+22 4.60718663e+28 5.68572000e+24]
 [5.32048241e+11 9.74480345e+09 1.81123908e+41]
 [5.54062238e+34 2.35385267e+17 2.35385267e+17]]


In [ ]:
#round/floor/ceil

print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[37. 86. 69.]
 [49. 70. 94.]]
[[28. 67. 68.]
 [33. 74.  9.]]
[[15. 94. 13.]
 [ 8. 18. 68.]]


# Indexing & slicing

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
print(a1[-1])

9


In [ ]:
print(a2[1,2])

6


In [ ]:
print(a3[1,0,1])

5


In [ ]:
#slicing
print(a1[2:5])

[2 3 4]


In [ ]:
print(a2[0,:])  #first row then col
print(a2[:,2])

[0 1 2 3]
[ 2  6 10]


In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

# Iterating

In [ ]:

for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
# for printing each item of 2d/3d array

for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
#reshape
#already discuss

In [ ]:
#transpose
np.transpose(a2) or # a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel  convert all dim into 1d
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [ ]:
#horizontal staking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5



array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [ ]:
#horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
#vertical splitting
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]